#if _NET_4 && _M_MSIL
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Assembly                 : System
// Runtime Version          : v4.0.30319
// Assembly Version         : 4.0.0.0
// Processor Architecture   : MSIL
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------


using Urasandesu.Prig.Framework;

[assembly: Indirectable(System.Diagnostics.Prig.PProcessBase.TokenOfStart)] 
[assembly: Indirectable(System.Diagnostics.Prig.PProcessBase.TokenOfStartString)] 
[assembly: Indirectable(System.Diagnostics.Prig.PProcessBase.TokenOfBeginOutputReadLine)] 
[assembly: Indirectable(System.Diagnostics.Prig.PProcessBase.TokenOfBeginErrorReadLine)] 
[assembly: Indirectable(System.Diagnostics.Prig.PProcessBase.TokenOfPriorityClassSetProcessPriorityClass)]

namespace System.Diagnostics.Prig
{
    public abstract class PProcessBase
    {
        internal const int TokenOfStart = 0x06002F2E; 
        internal const int TokenOfStartString = 0x06002F36; 
        internal const int TokenOfBeginOutputReadLine = 0x06002F40; 
        internal const int TokenOfBeginErrorReadLine = 0x06002F41; 
        internal const int TokenOfPriorityClassSetProcessPriorityClass = 0x06002EF6;
    }
}
#endif
